version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: tasks-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - tasks-network

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin4-tasks
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    networks:
      - tasks-network

networks:
  tasks-network: